/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Jan 21 2017
 * Processor: PIC18F4620
 * Compiler:  CCS for PIC
 */

#include <18F4620.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
