// external declaration of sound table:

extern far cdata SNDTBL_AUDIOVASE;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_zero;
extern far cdata SX_one;
extern far cdata SX_two;
extern far cdata SX_three;
extern far cdata SX_four;
extern far cdata SX_five;
extern far cdata SX_six;
extern far cdata SX_seven;
extern far cdata SX_eight;
extern far cdata SX_nine;
extern far cdata SX_hello_please_say_a_command;
extern far cdata SX_please_say_a_command;
extern far cdata SX_command_accepted;
extern far cdata SX_who_would_you_like_to_call;
extern far cdata SX_calling;
extern far cdata SX_say_answer_to_answer_the_call;
extern far cdata SX_say_reject_to_reject_the_call;
extern far cdata SX_say_send_to_place_the_call;
extern far cdata SX_you_have_an_incoming_call;
extern far cdata SX_turning_off_led;
extern far cdata SX_turning_on_LED;
extern far cdata SX_turning_off_light_bulb;
extern far cdata SX_turning_on_light_bulb;
extern far cdata SX_is_trying_to_reach_you;
extern far cdata SX_doctor;

// constants defining sounds as entries in the sound table:

#define SND_zero                1
#define SND_one                 2
#define SND_two                 3
#define SND_three               4
#define SND_four                5
#define SND_five                6
#define SND_six                 7
#define SND_seven               8
#define SND_eight               9
#define SND_nine                10
#define SND_hello_please_say_a_command 11
#define SND_please_say_a_command 12
#define SND_command_accepted    13
#define SND_who_would_you_like_to_call 14
#define SND_calling             15
#define SND_say_answer_to_answer_the_call 16
#define SND_say_reject_to_reject_the_call 17
#define SND_say_send_to_place_the_call 18
#define SND_you_have_an_incoming_call 19
#define SND_turning_off_led     20
#define SND_turning_on_LED      21
#define SND_turning_off_light_bulb 22
#define SND_turning_on_light_bulb 23
#define SND_is_trying_to_reach_you 24
#define SND_doctor              25

