// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2009 Sensory, Inc. All Rights Reserved.
// Generated by Nicola on Tue Nov 08 16:41:48 2016 - GUI 3.1.14

extern far cdata gsearch_comm_HomeAutomation_3;
#ifndef NN_HOMEAUTOMATION_3
#define NN_HOMEAUTOMATION_3
extern far cdata nn_HomeAutomation_3;
#endif

#define G_comm_HomeAutomation_3_SILENCE                   (0)
#define G_comm_HomeAutomation_3_DOOR                      (1)
#define G_comm_HomeAutomation_3_T_V                       (2)
#define G_comm_HomeAutomation_3_TEMPERATURE               (3)
#define G_comm_HomeAutomation_3_WINDOW                    (4)
#define G_comm_HomeAutomation_3_MUSIC                     (5)
#define G_comm_HomeAutomation_3_LIGHT                     (6)
#define G_comm_HomeAutomation_3_TIMER                     (7)
#define G_comm_HomeAutomation_3_OVEN                      (8)
#define G_comm_HomeAutomation_3_WASHING_MACHINE           (9)
#define G_comm_HomeAutomation_3_DISH_WASHER               (10)
#define G_comm_HomeAutomation_3_nota                      (11)

/* ======================= Build Log ========================= */
/* Timestamp:                    Tue Nov 08 16:41:48 2016 */
/* Licensed To:                  GEPDBGSBN2 */
/* QT2SI GUI:                    3.1.14 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults (581 states) */
/* Pronunciation_1:              {door {. d >1 9 .}} */
/* Pronunciation_2:              {{t v} {. t i1 . . v i1 .}} */
/* Pronunciation_3:              {temperature {. t E1 m . p & . 9 & . tS & 9 .}} */
/* Pronunciation_4:              {window {. w I1 n . d oU .}} */
/* Pronunciation_5:              {music {. m j u1 . z I k .}} */
/* Pronunciation_6:              {light {l aI1 t}} */
/* Pronunciation_7:              {timer {. t aI1 . m & 9 .}} */
/* Pronunciation_8:              {oven {. ^1 . v ix n .}} */
/* Pronunciation_9:              {{washing machine} {. w A1 . S I ng . . m ^ . S i1 n .}} */
/* Pronunciation_10:              {{dish washer} {. d I1 S . . w A1 . S & 9 .}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  10406 */
/* Grammar Size (bytes):         1417 */
/* Total Number of States:       158 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
