// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2009 Sensory, Inc. All Rights Reserved.
// Generated by Nicola on Tue Nov 08 16:28:59 2016 - GUI 3.1.14

extern far cdata gsearch_trig_HomeAutomation_1;
#ifndef NN_HOMEAUTOMATION_1
#define NN_HOMEAUTOMATION_1
extern far cdata nn_HomeAutomation_1;
#endif

#define G_trig_HomeAutomation_1_SILENCE                   (0)
#define G_trig_HomeAutomation_1_OK_EASYVEEAR              (1)
#define G_trig_HomeAutomation_1_nota                      (2)

/* ======================= Build Log ========================= */
/* Timestamp:                    Tue Nov 08 16:28:59 2016 */
/* Licensed To:                  GEPDBGSBN2 */
/* QT2SI GUI:                    3.1.14 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults (581 states) */
/* Pronunciation_0:              {{ok easyveear} {oU . k eI1 . . i1 . z i . v I2 9}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Reject more utterances */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  8462 */
/* Grammar Size (bytes):         287 */
/* Total Number of States:       34 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
