// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2009 Sensory, Inc. All Rights Reserved.
// Generated by Nicola on Tue Nov 08 16:38:19 2016 - GUI 3.1.14

extern far cdata gsearch_comm_HomeAutomation_2;
#ifndef NN_HOMEAUTOMATION_2
#define NN_HOMEAUTOMATION_2
extern far cdata nn_HomeAutomation_2;
#endif

#define G_comm_HomeAutomation_2_SILENCE                   (0)
#define G_comm_HomeAutomation_2_TURN_ON                   (1)
#define G_comm_HomeAutomation_2_SWITCH_OFF                (2)
#define G_comm_HomeAutomation_2_INCREASE                  (3)
#define G_comm_HomeAutomation_2_DECREASE                  (4)
#define G_comm_HomeAutomation_2_OPEN                      (5)
#define G_comm_HomeAutomation_2_CLOSE                     (6)
#define G_comm_HomeAutomation_2_START                     (7)
#define G_comm_HomeAutomation_2_STOP                      (8)
#define G_comm_HomeAutomation_2_nota                      (9)

/* ======================= Build Log ========================= */
/* Timestamp:                    Tue Nov 08 16:38:19 2016 */
/* Licensed To:                  GEPDBGSBN2 */
/* QT2SI GUI:                    3.1.14 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults (581 states) */
/* Pronunciation_1:              {{turn on} {. t 3r1 n . . A1 n .}} */
/* Pronunciation_2:              {{switch off} {. s w I1 tS . ( . >1 f . | . A1 f . )}} */
/* Pronunciation_3:              {increase {. I n . k 9 i1 s .}} */
/* Pronunciation_4:              {decrease {. d i1 . k 9 i s .}} */
/* Pronunciation_5:              {open {. oU1 . p & n .}} */
/* Pronunciation_6:              {close {. k l oU1 s .}} */
/* Pronunciation_7:              {start {. s t A1 9 t .}} */
/* Pronunciation_8:              {stop {. s t A1 p .}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  8174 */
/* Grammar Size (bytes):         1078 */
/* Total Number of States:       115 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
