// external declaration of sound table:

extern far cdata SNDTBL_DEMO;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_Access_denied;
extern far cdata SX_Access_granted;
extern far cdata SX_Hello;
extern far cdata SX_Please_repeat;
extern far cdata SX_Please_say_your_password;
extern far cdata SX_Hello_give_command;
extern far cdata SX_Please_say_name;
extern far cdata SX_Pwd_activated;

// constants defining sounds as entries in the sound table:

#define SND_Access_denied       1
#define SND_Access_granted      2
#define SND_Hello               3
#define SND_Please_repeat       4
#define SND_Please_say_your_password 5
#define SND_Hello_give_command  6
#define SND_Please_say_name     7
#define SND_Pwd_activated       8

