// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2009 Sensory, Inc. All Rights Reserved.
// Generated by Nicola on Tue Nov 08 16:28:59 2016 - GUI 3.1.14

extern far cdata gsearch_comm_HomeAutomation_1;
#ifndef NN_HOMEAUTOMATION_1
#define NN_HOMEAUTOMATION_1
extern far cdata nn_HomeAutomation_1;
#endif

#define G_comm_HomeAutomation_1_SILENCE                   (0)
#define G_comm_HomeAutomation_1_NEXT                      (1)
#define G_comm_HomeAutomation_1_PREVIOUS                  (2)
#define G_comm_HomeAutomation_1_STOP                      (3)
#define G_comm_HomeAutomation_1_PLAY                      (4)
#define G_comm_HomeAutomation_1_PAUSE                     (5)
#define G_comm_HomeAutomation_1_RECORD                    (6)
#define G_comm_HomeAutomation_1_nota                      (7)

/* ======================= Build Log ========================= */
/* Timestamp:                    Tue Nov 08 16:28:59 2016 */
/* Licensed To:                  GEPDBGSBN2 */
/* QT2SI GUI:                    3.1.14 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults (581 states) */
/* Pronunciation_1:              {next {. n E1 k s t .}} */
/* Pronunciation_2:              {previous {. p 9 i1 . v i . & s .}} */
/* Pronunciation_3:              {stop {. s t A1 p .}} */
/* Pronunciation_4:              {play {. p l eI1 .}} */
/* Pronunciation_5:              {pause {. p >1 z .}} */
/* Pronunciation_6:              {record {. 9 E1 . k & 9 d .}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  8462 */
/* Grammar Size (bytes):         821 */
/* Total Number of States:       86 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
