// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2008 Sensory, Inc. All Rights Reserved.
// Generated by Paolo on Thu Nov 07 10:38:16 2013 - GUI 3.1.7

extern far cdata gsearch_comm_demo;
#ifndef NN_DEMO
#define NN_DEMO
extern far cdata nn_demo;
#endif

#define G_comm_demo_SILENCE                   (0)
#define G_comm_demo_PASSWORD_SETUP            (1)
#define G_comm_demo_PASSWORD_ACTIVATED        (2)
#define G_comm_demo_CURTAIN_UP                (3)
#define G_comm_demo_CURTAIN_DOWN              (4)
#define G_comm_demo_LIGHTS_ON                 (5)
#define G_comm_demo_LIGHTS_OFF                (6)
#define G_comm_demo_nota                      (7)

/* ======================= Build Log ========================= */
/* Timestamp:                    Thu Nov 07 10:38:16 2013 */
/* Licensed To:                  SantaClaraRep */
/* QT2SI GUI:                    3.1.7 */
/* Fluent Chip:                  3.1.16 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults and Kids (464 states) */
/* Pronunciation_1:              {{password setup} {. p @1 s . w 3r2 d . . s E1 t . ^2 p .}} */
/* Pronunciation_2:              {{password activated} {. p @1 s . w 3r2 d . . @1 k . t I . v eI . t ix d .}} */
/* Pronunciation_3:              {{curtain up} {. k 3r1 . t & n . . ^1 p .}} */
/* Pronunciation_4:              {{curtain down} {. k 3r1 . t & n . . d aU1 n .}} */
/* Pronunciation_5:              {{lights on} {. l aI1 t s . . A1 n .}} */
/* Pronunciation_6:              {{lights off} {. l aI1 t s . ( . >1 f . | . A1 f . )}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  9329 */
/* Grammar Size (bytes):         1048 */
/* Total Number of States:       121 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
